platform :ios, '9.0'

target 'QuizApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizApp

    pod 'SwiftyJSON', '4.2.0'
    pod 'Alamofire', '4.7.3'
    pod 'PieCharts'

end
